chaisql/chai

cmd/genji/shell/shell.go
=> Fixes Issue #46 to execute sql script

document/value.go, document/value_test.go
`Value.Compare()` compares two values performing best-effort comparisons.
I wrote it to fix #60, but the final solution there turned out to be much better. In any case, I think this could be helpful enhancement, so here it is.
=> added Value.Compare()

database/config.go, database/config_test.go, database/table.go, database/transaction.go, database/transaction_test.go, sql/parser/alter.go, sql/parser/alter_test.go, sql/parser/parser.go, sql/query/alter.go, sql/query/alter_test.go, sql/scanner/scanner.go, sql/scanner/scanner_test.go, sql/scanner/token.go
This PR fixes #95. 
We can now rename a table and all indexes linked to the table are updated as well.
=> Add ALTER TABLE ... RENAME TO feature

database/table.go, database/table_test.go, sql/parser/parser.go, sql/parser/reindex.go, sql/parser/reindex_test.go, sql/query/reindex.go, sql/query/reindex_test.go, sql/scanner/scanner_test.go, sql/scanner/token.go
=> Add support for ReIndex statement

document/document.go, document/document_test.go, sql/parser/update.go, sql/parser/update_test.go, sql/planner/tree.go, sql/query/update_test.go
This PR reverts the changes introduced by genjidb/genji#127 as they still contain a few bugs.
Issue https://github.com/genjidb/genji/issues/84 will be postponed to release v0.8
=> Revert "Allow dot notation for update set."

cmd/genji/shell/shell.go, sql/parser/drop.go
This PR fixes #157 with indexes suggestion for `DROP INDEX` statement.
=> Index suggestion

document/scan.go, document/scan_test.go
=> Fix scan of encoded documents and arrays

cmd/genji/go.mod, cmd/genji/go.sum, cmd/genji/insert.go, cmd/genji/insert_test.go, cmd/genji/main.go, document/array.go
=> Add command insert to cli command

sql/query/expr/function.go, sql/query/select_test.go
=> Add SUM aggregator

cmd/genji/shell/shell.go
This PR allows disabling colored prompt by setting NO_COLOR environment variable. It also allows disabling history dumping and loading (that is, only I/O) in a similar fashion.
See https://no-color.org
=> Respect NO_COLOR and NO_HISTORY environment variables

document/scan.go, document/scan_test.go
=> Be more forgiving when scanning null values in StructScan

cmd/genji/insert.go, cmd/genji/main.go
=> Automatically create a database and a table with genji insert option '-a'

cmd/genji/shell/command.go, cmd/genji/shell/command_test.go, cmd/genji/shell/shell.go, sql/query/insert_test.go
This PR fix #181.
All database is displayed or the given table. 
Double are now outputted even with `.0` decimal
=> .dump command 

cmd/genji/shell/command.go, database/config.go
This fixes #214.
I added `t.tableInfos[indexStoreName]` and fixed the `.indexes` command.
=> Expose __genji_indexes table.

sql/parser/expr.go, sql/parser/options.go, sql/parser/parser.go, sql/query/expr/function.go
=> Add AVG() aggregate function, allow to add custom via API 

sql/parser/expr.go, sql/parser/select_test.go
=> Fix parentheses parsing

.travis.yml
=> Fix CI test script for nested modules

document/value.go, document/value_test.go
=> Display doubles with a decimal point

cmd/genji/shell/command.go, database/config.go, database/config_test.go, database/errors.go, database/transaction_test.go, sql/query/alter_test.go, sql/query/drop.go, sql/query/reindex.go
Hello, 
I changed my pull request, now it's passing in all the tests and building in travis CI.
Closes #238
=> Explicit message error for ErrTableNotFound

document/value.go, document/value_test.go, sql/parser/parser_test.go
=> Fixes divide by zero panic

document/value.go, document/value_test.go
=> Add trailing .0 for double value when needed

document/create_test.go, document/document_test.go
This PR move some tests  from `document_test.go` into `create_test.go`.
=> Move TestNewFromMap into create_test.go

sql/query/expr/path.go
=> Return missing error in FieldSelector.Eval

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
This PR adds issue templates for bug reports and feature requests.
Closes #293
=> Add simple issue templates

db.go, engine/badgerengine/engine.go, engine/badgerengine/store.go, engine/boltengine/engine.go, engine/boltengine/store.go, engine/enginetest/testing.go, engine/memoryengine/engine.go, engine/memoryengine/store.go, new.go, new_wasm.go
This PR fixes #224 by adding support for cancellation to engines.
=> Add cancellation in engines

sql/planner/tree.go, sql/query/select_test.go
=> Fix panic when optimizer returns empty tree

sql/planner/input.go, sql/planner/optimizer.go
=> Move index fetching to bind stage

sql/planner/optimizer.go, sql/planner/optimizer_test.go
=> Prevent index usage with IN operator and indexed right operand

document/iterator.go, sql/query/expr/function.go, sql/query/select_test.go
=> Fix aggregation result for empty input

document/create.go, document/document_test.go
I think that converting struct to Document is a very complex topic (just look at json/encoding), but #260 introduced behavior that is incompatible with one that was previously (see tests).
=> Fix creating document from struct with known types

database/table.go, database/table_test.go, document/create.go, document/document.go, document/value.go, sql/query/insert.go, stream/iterator.go, stream/iterator_test.go, stream/operator.go, stream/operator_test.go, testutil/document.go
This PR adds some stream operators that interact with indexes and tables.
=> Add io stream operators

document/scan.go, document/scan_test.go
=> Fix scanning of slice of structs

cmd/genji/shell/command.go, cmd/genji/shell/command_test.go
Hey @asdine, I was skimming through the issues and stumbled on this one: #329 
Usually, I'd ask first, but the fix seemed rather simple so I went for it.
Please tell me if there's anything missing or if you thought about implementing this in a different way!
=> Add default field constraint support to Dump command 

cmd/genji/dump.go, cmd/genji/dump_test.go, cmd/genji/main.go, cmd/genji/shell/command.go, cmd/genji/shell/command_test.go, cmd/genji/shell/shell.go
=> Dump command.

document/value_encoding.go, document/value_test.go
=> Fix binary encoding failing on consecutive ints

cmd/genji/main.go, cmd/genji/restore.go, cmd/genji/restore_test.go
This a proposal for #321 . This PR allows only the full database restoration from a file.
=> Add restore command.

cmd/genji/dbutil/db.go, cmd/genji/go.mod, cmd/genji/go.sum, cmd/genji/shell/shell.go
This PR ensures the database is opened during startup and displays a better error message if the database is locked.
Fixes #365
=> Handle locked databases correctly

database/catalog.go, database/catalog_test.go
=> Fix panic after index drop

cmd/genji/shell/shell.go
Added a missing error handling in the shell.
=> Add error handling in the shell

document/scan.go, document/scan_test.go
=> Fix blob to byte array decoding

sql/driver/driver.go, sql/driver/driver_test.go
=> Fix scanning of time.Time in sql/driver

document/document.go, query/insert_test.go, sql/parser/insert.go, sql/parser/insert_test.go, sql/parser/select.go, stream/operator.go, stream/operator_test.go
This adds support for `INSERT ... SELECT`. The only limitation compared to other databases is that inserting and selecting from the same table is prohibited.
=> Add INSERT ... SELECT

cmd/genji/dbutil/dump.go, cmd/genji/dbutil/dump_test.go, cmd/genji/shell/command.go, cmd/genji/shell/shell.go
=> Add .schema command.

cmd/genji/shell/shell.go
=> Fix typos.

cmd/genji/go.sum, engine/badgerengine/go.sum, fuzz/go.sum, go.mod, go.sum, query/gen_insert_statements_test.go, query/gen_insert_statements_test.sql, query/gen_insert_with_select_test.go, query/gen_insert_with_select_test.sql, testutil/gen.go
Here what it outputs now, when there is a type difference between what is want and what we got :) 
I had to resort to using basic structure to represent the data because if we did not, we'd get a diff with both documents in their entirety, which defeats the purpose of having pretty diffs. 
I think we can do **much** better, but it's a fairly acceptable start :) 
--- FAIL: TestGenInsertStatements/insert_with_types_constraints/CREATE_TABLE_test_tc( (0.00s)
gen_insert_statements_test.go:766: 
Error Trace:	gen.go:118
gen_insert_statements_test.go:766
Error:      	mismatched documents, (-want, +got)
Test:       	TestGenInsertStatements/insert_with_types_constraints/CREATE_TABLE_test_tc(
Messages:   	  []*testutil.Val{
&{
Type: "document",
V: []testutil.Field{
... // 4 identical elements
{Name: …
=> Use go-cmp to improve the output of the generated sql tests

engine/memoryengine/engine.go, engine/memoryengine/store.go
Instead of relying on a goroutine, the memoryengine now
adds reads from the underlying btree in batch and then
iterates over the cached items.
This makes the memoryengine smaller and much faster.
```
name                            old time/op    new time/op    delta
MemoryEngineStoreScan/00001-12    4.04µs ± 0%    0.23µs ± 0%  -94.21%  (p=1.000 n=1+1)
MemoryEngineStoreScan/00010-12    6.86µs ± 0%    0.37µs ± 0%  -94.60%  (p=1.000 n=1+1)
MemoryEngineStoreScan/00100-12    37.3µs ± 0%     1.9µs ± 0%  -94.96%  (p=1.000 n=1+1)
MemoryEngineStoreScan/01000-12     335µs ± 0%      21µs ± 0%  -93.68%  (p=1.000 n=1+1)
MemoryEngineStoreScan/10000-12    3.28ms ± 0%    0.24ms ± 0%  -92.77%  (p=1.000 n=1+1)
name                            old alloc/op   new alloc/op   delta …
```
=> Simplify memoryengine

cmd/genji/dbutil/dump.go, cmd/genji/dbutil/schema.go, cmd/genji/shell/command.go, driver/driver_test.go, internal/catalog/cache.go, internal/catalog/catalog.go, internal/catalog/catalog_test.go, internal/catalog/storage.go, internal/database/catalog.go, internal/database/constraint.go, internal/database/database.go, internal/database/index.go, internal/database/info.go, internal/database/sequence_test.go, internal/database/table.go, internal/database/table_test.go, internal/query/statement/create.go, internal/query/statement/drop_test.go, internal/query/statement/gen_insert_statements_test.go, internal/query/statement/gen_insert_statements_test.sql, internal/stringutil/custom.go, open_test.go
Each table with no primary key now creates a sequence to manage docids
=> Create sequence for docids

cmd/genji/commands/insert.go
`engine` option is no longer supported.
=> update cli insert usage

document/document.go, document/document_test.go
=> CloneValue: use copy instead of  iterate.

internal/sql/parser/alter.go, internal/sql/parser/delete.go, internal/sql/parser/drop.go
=> parser: fix interface conversion.

internal/expr/expr.go, internal/expr/functions/builtins.go, internal/expr/functions/scalar_definition.go, internal/query/statement/stream.go, internal/stream/index/scan_test.go, internal/testutil/expr.go, types/types.go
- typo fixes
- docstring format fixes
- unused variables fixes
- introducing first usages of testutil.ParseDocumentPaths function, which was previously unused
I was reading the code and decided to add some changes to make it a little bit better :)
Test plan:
Existing tests should pass
=> clean up some docs and code, including:
