chaisql/chai

document/array.go, document/document.go, document/scan.go, document/value.go, document/value_test.go
This PR does the following:
* Refactor `document.NewValue()` merging it with `reflectValueToValue()` as both were very similar, and `NewValue()` would not recognize simple type definitions, such as `type myString string` as valid, while `reflectValueToValue()` would and created inconsistencies.
* Added an error type to wrap `ErrUnsupportedType` so this can be checked outside explicitly.
* Upgraded tests to check user types are covered.
=> Refactor NewValue and support type definitions of basic types

index/index.go, sql/query/plan.go, sql/query/select_test.go
This PR fixes a tricky bug that happens when running queries with an `ORDER BY` clause in which the field is a numeric value and there is no index for that field.
The bug happens because in `plan.go` in the the wrong byte-encoded representation of the value was used, and that does not tell if a number is bigger or smaller than another one. For example:
`0` is encoded as `[]byte{128}`
`100` is encoded as `[]byte{228}`
`200` is encoded as `[]byte{128, 200}`
Doing a pure byte comparison yields that `100` is greater than `200`, because `[]byte{228}` is considered greater than `[]byte{128, 200}` by `bytes.Compare()`.
To fix the issue, I exported the `index.EncodeFieldToIndexValue()` so the same function is used for generating the index and for ordering when there is no index.
I also changed …
=> Fix ordering by numeric values when there is no index

document/document.go, document/document_test.go, document/encoding/encoding_test.go, document/scan.go, document/value.go
This PR does the following:
* Enables embedded struct fields in `document.NewFromStruct()` so they are considered rather than ignored. 
* Enable any map type with string key in `document.NewFromMap()`. This allows users to pass any kind of map with a string key instead of just `map[string]interface{}`
* Better error messages for `document.ErrUnsupportedType` errors.
=> Improve struct scanning

cmd/genji/shell/shell.go
This is a potential fix for #67.
Actually, if a function is not yet supported, an error will be returned from the `query` package. This error is not a `ParseError` which makes the shell panic.
From now on, we assert that the error holds the concrete `ParseError` type, if not, we just return an empty slice of suggestions.
=> [Genji/shell] Assert that the error holds the concrete ParseError type

cmd/genji/main.go, cmd/genji/shell/shell.go
This pull-request fixes a couple of issues I had when working with the genji cli tool.
I ran into a compile error at first, because of a mismatched type between the cli.Flag interface and the cli.BoolFlag type. Correcting that was simple and allowed the app to compile after making the change.
When working with the cli tool, I was expecting to find a way to exit or quit the cli from the interactive prompt like in other database cli tools. Having not found a method to quit the application from the prompt, I added the `.exit` command to give an easy way to quit the app.
=> Simple cli tool fixes 

db.go
Since that the `ErrDocumentNotFound` error returned from `QueryDocument` is in a different package, I think it's better to add a reference to this package in the godoc.
I had to look for it in the code to see where it is declared, probably more straightforward now.
=> Add package reference to the error returned in the godoc

sql/query/update.go, sql/query/update_test.go
This is a proposal to fix #69. 
I have moved the `GetByField` below in the flow, depending on the returned value, the field will be replaced or added. 
Tests have been improved along the way.
=> UPDATE ... SET sets fields on every document

database/table.go, sql/parser/update.go, sql/parser/update_test.go, sql/query/update.go, sql/query/update_test.go, sql/scanner/scanner_test.go, sql/scanner/token.go
This PR adds support for `UNSET` clause.
`Table.ValidateConstraints` has been exposed because it's needed for validating the constraints when unsetting a field. 
Tests have been improved along the way as well.
=> Add support for UNSET clause

database/transaction.go, document/encoding/encoding.go, document/encoding/format.go, document/value.go, sql/parser/expr.go, sql/query/expr/param.go
The main purpose of this PR is to improve how errors are returned from `Value.ConvertTo`.
Before, if we tried to convert an incompatible type to an int8 the error was: 
`can't convert "text" to int64`. 
It was a bit obscure but now, the returned error is:
`cannot convert "text" to "int8": type "text" incompatible with integer`
Next to this change, I've made the code more consistent in the errors message:
- before we had a mix of `can't` and `cannot`, now we only have `cannot`
- before the types were sometimes surrounded by double quotes, sometimes not, now they are all surrounded by `""`
=> A bit of cleaning

database/config.go, database/config_test.go, database/table_test.go, database/transaction.go, database/transaction_test.go, engine/engine.go, sql/query/drop_test.go
This PR fixes #99.
The fix is really trivial, just checking that the index we are iterating on is associated to the table we want to drop.
I take the opportunity to improve tests for `sql/query/drop.go` and I also added a method for listing the indexes (it's a good start for #100).
=> Dropping a table should remove only indexes associated to that table

sql/parser/expr.go, sql/parser/insert.go, sql/parser/insert_test.go, sql/query/insert.go
For INSERT, some checks were done during execution time while they could have been done during parsing time. This PR fixes that for the two following errors:
```sql
// not the same number of elements, len(a, b)!= len(1, 2, 3)
INSERT INTO foo (a, b) VALUES (1, 2, 3)
// bad input:
// list of fields (a, b) with document value {a: 1}
INSERT INTO foo (a, b) VALUES (1, 2), {a: 1}
// expecting documents, got expression list (1, 2)
INSERT INTO foo VALUES (1, 2)
```
=> Better INSERT parsing

database/config.go, database/config_test.go, database/database.go, database/table.go, database/table_test.go, engine/badgerengine/store.go, engine/enginetest/testing.go
This PR changes the way the default document key is generated on tables without primary keys. Previously, multiple transactions executed at the same time could generate the same default keys using the Badger engine, only one transaction would work and the other ones would fail with a `Transaction Conflict`.
This PR makes some major changes:
- it introduces the concept of `docid`, the equivalent of SQLite's `rowid`. Whenever a document is inserted in a table that doesn't contain a primary key, a docid is generated (that's already the current behavior, it's just that it has a new name now). All mentions to "docid" refer specifically to that generated default key, not the user-chosen primary key.
- the next docid is determined by getting the largest docid of the table, then incremented
- the …
=> Safer default document key

document/array.go, document/array_test.go
This PR fixes a bug that made the `ValueBuffer#Copy` method to append nested arrays and nested documents at the end of the array.
Before:
```sql
genji> create table foo (a.1 int primary key);
genji> insert into foo (a) VALUES ([1, 2, [3, 4]]);
genji> select * from foo;
{
"a": [
1,
2,
[
3,
4
],
[
3,
4
]
]
}
```
After:
```sql
genji> create table foo (a.1 int primary key);
genji> insert into foo (a) VALUES ([1, 2, [3, 4]]);
genji> select * from foo;
{
"a": [
1,
2,
[
3,
4
]
]
}
```
Thank you @tzzed for spotting this bug!
=> Fix ValueBuffer#Copy method

sql/planner/replacement.go, sql/query/update_test.go
This PR fixes #107 by doing a deep copy of the document instead of a shallow copy.
Nodes reuse memory between each iteration and the Replacement Node was storing each document in a buffer before writing them into the table, which caused it to write corrupted docs.
=> Deep copy documents in Replacement node

sql/parser/select.go, sql/parser/select_test.go
This PR fixes #64 by adding a special case in the parser for FieldSelectors. It makes sure we are always displaying the unquoted version of these fields instead of the raw version entered by the user.
=> Display unquoted field names in result fields

document/value.go, document/value_test.go
This fixes https://github.com/genjidb/genji/issues/105 by returning `NULL` whenever we try to evaluate an arithmetic operator with incompatible types.
=> Make arithmetic operators always return null on incompatible types

database/config.go, database/config_test.go, database/table.go, database/table_test.go, database/transaction.go, sql/parser/create.go, sql/parser/create_test.go, sql/planner/projection.go, sql/query/create.go, sql/query/create_test.go, sql/query/expr/expr.go, sql/query/expr/expr_test.go, sql/query/expr/function.go, sql/query/expr/function_test.go, sql/query/plan.go
As suggested in https://github.com/genjidb/genji/pull/110#discussion_r451303589, this PR removes the `TableConfig` type and replaces it by the `TableInfo` one.
`TableInfo` now holds _all_ informations regarding a table.
=> Replace TableConfig by TableInfo

cmd/genji/shell/shell.go
This PR fixes #106 by adding `TrimSpace` of input.
The command is ignored if the input is empty.
=> Ignore Input shell with whitespaces only or no input

sql/parser/expr.go, sql/parser/expr_test.go, sql/query/expr/expr.go, sql/query/insert_test.go
This PR changes how parentheses were parsed by the parser. Previously, they were considered as lists of expressions, which after evaluation turned into an array. This behaviour prevented us from using parentheses as arithmetic sub expressions.
Before:
```sql
genji> select ((10 + 5 + 5) * 4) / 2;
{
"((10 + 5 + 5) * 4) / 1": null
}
genji> select ((10 + 5 + 5) * 4);
{
"((10 + 5 + 5) * 4)": [
null
]
}
```
After:
```sql
genji> select ((10 + 5 + 5) * 4) / 2;
{
"((10 + 5 + 5) * 4) / 1": 40
}
genji> select ((10 + 5 + 5) * 4);
{
"((10 + 5 + 5) * 4)": 80
}
```
=> Fix parentheses behaviour

db.go, sql/query/create_test.go
`ViewTable` and `UpdateTable` used to be useful when Genji was doing code generation and before the introduction of SQL. They were used to limit the number of lines of generated code.
They no longer make sense now as we want to encourage users to use SQL as much as possible.
If there is a need to access tables, there is still the `View` and `Update` methods.
Please let me know if you think otherwise
=> Remove unnecessary db methods

database/config.go, database/table.go, document/encoding/encoding.go, document/encoding/msgpack/codec.go, document/json.go, document/scan.go, document/value.go
The names `ConvertToBlob` and `ConvertToText` don't really make sense because these functions are used to get respectively get a []byte and string out of a value.
=> Rename convert methods

cmd/genji/shell/command.go, cmd/genji/shell/command_test.go, cmd/genji/shell/shell.go, database/config.go, database/table.go, database/transaction.go, sql/planner/optimizer.go, sql/query/plan.go
This PR fixes #100. Two options for the command `.Indexes` and `.Indexes <table name>` are implemented. Tests `.tables` and `.indexes` are added. 
```
genji> .indexes
main skill index on users(skills.0)
idx_nen on users(nen)
genji>
```
Refactoring of  `struct Index`. Let me know what you think about it
=> Command .indexes displaying indexes of database or a table.

cmd/genji/shell/command.go, database/config.go, database/config_test.go, database/database.go, database/transaction.go, database/transaction_test.go, sql/query/drop_test.go
This PR makes `tableInfoStore` keep table information in memory. Table information is loaded at database startup and kept up to date every time a table is created, altered or dropped.
This change allows us to have access to table information without the need for a transaction, which is handy if we need to use this during parsing time.
It also fixes a bug where duplicate generated store id was overwritten.
=> Store table information in memory

database/table.go, sql/planner/projection.go
This change adds a few optimizations on how memory is handled during iteration. It removes some unnecessary memory allocations by reusing struct values and buffers between each iteration.
It also lazily calls `ValueCopy` so that it's only called when we want to actually read the document. This is useful for queries that don't necessarily need to read some documents (i.e. `SELECT COUNT(*)`)
=> Read values from store lazily

sql/query/expr/literal.go, sql/query/insert_test.go
This PR fixes #65 by adding the current field buffer to the eval stack whenever we are evaluating a KVPairs into a document.
=> Add reference to current document to eval context

database/transaction.go, db.go, db_test.go, sql/driver/driver.go, sql/query/query.go
This PR removes the transaction promotion feature. This feature was wrongly implemented, as it's not currently possible to promote a transaction in Bolt or Badger.
=> Remove transaction promotion

database/config.go, database/config_test.go, database/database.go, database/table.go, database/transaction.go, database/transaction_test.go
Since we started keeping table information in memory, we introduced a bug that prevents us from creating a table if this one has already been created during a transaction, then that transaction rolls back:
- Tx A creates a table named `foo`
- Tx A rolls back
- Tx B creates a table name `foo` -> Table already exists
This PR introduces transaction isolation at the tableInfoStore level by using transaction ids to hide tables that haven't been committed from other transactions.
That way, transactions are not aware of tables that have been created in transactions that haven't been committed yet, EXCEPT when other transactions attempt to create a table with the same name.
=> Fix bad tableInfoStore state on rollback

cmd/genji/shell/command.go, database/config.go, database/config_test.go, database/table.go, database/transaction.go, database/transaction_test.go, sql/query/alter_test.go, sql/query/delete_test.go, sql/query/drop_test.go, sql/query/insert_test.go, sql/query/reindex_test.go, sql/query/update_test.go
This PR allows running SELECT queries against the `__genji_tables` table, which manages the `tableInfoStore`.
=> Expose __genji_tables

database/config.go, database/config_test.go
This PR adds a prefix to every created table store. It also fixes a panic when decoding a tableInfo.
Fixes #73
=> Add prefix to table stores

cmd/genji/shell/command.go, cmd/genji/shell/shell.go
This PR fixes #158. 
The `.help` command list all the available dot command.
A message `Enter ".help" for usage hints` is displayed at genji launch. 
```
On-disk database using BoltDB engine at path my.db.
**.**
genji> .help
.exit 			        Exit genji program
.help 			        List all available dot commands
.indexes [table_name] 	Display all indexes of the database or that the given table_name
.tables 		                 List names of tables
````
=> Add .help command.

document/document.go, document/document_test.go, sql/parser/update.go, sql/parser/update_test.go, sql/planner/tree.go, sql/query/update_test.go
This PR fixes #84 by a deep recursive course of the document based on the ValuePath.
#Set method is now taking a ValuePath.
=> Allow dot notation for update set.

cmd/genji/shell/shell.go, sql/parser/delete.go, sql/parser/drop.go, sql/parser/select.go
This PR fixes the #143 .
Tables are listed after `FROM` keyword in `SELECT and DELETE` statements.
Added to `DROP TABLE` statement too.
If there is no tables the word `table_name` is displayed:
```
genji> SELECT * FROM table_name
```
=> Table suggestion after FROM keyword

sql/parser/alter.go, sql/parser/insert.go, sql/parser/update.go
Fix #143 with suggestions for `ALTER`,  `UPDATE` and `INSERT` statements.
=> Add tables suggestion to the CLI

engine/badgerengine/engine.go, engine/badgerengine/store.go, engine/boltengine/store.go, engine/engine.go, engine/enginetest/testing.go, engine/memoryengine/engine.go, engine/memoryengine/store.go, index/index.go, index/index_test.go, index/list.go, key/encoding.go, key/encoding_test.go
This PR fixes #170 by changing how list indexes are implemented. Previously, each couple _value to index / key_ was stored in a store as following:
| store key | store value |
| - | - |
| `value to index`+`separator`+`key of the associated document` | nil |
This used to be valued as some point but this now has some obvious issues as the separator can be contained in both the value to index and the key of the document, making it impossible to determine where the separator is.
The new implementation uses a new method added to the engines called `NextSequence()`, which is responsible of returning a monotonically increasing integer.
This integer will be encoded and appended to every value to index, while the document key will be stored in the value of the store:
| store key | store value |
| …
=> Fix list index implementation

database/config.go
This PR fixes how the `pk()` function works with `__genji_tables`.
It adds information about the primary key of that table, so that pk can pick it up correctly.
Before:
```sql
genji> create table foo;
genji> create table bar(a integer);
genji> SELECT pk(), * from __genji_tables;
json: error calling MarshalJSON for type document.jsonDocument: cannot decode buffer to uint64
``` 
After:
```sql
genji> create table foo;
genji> create table bar(a integer);
genji> SELECT pk(), * from __genji_tables;
{
"pk()": "bar",
"table_name": "bar",
"store_id": "dF9LVloqBA==",
"field_constraints": [
{
"path": [
"a"
],
"type": 16,
"is_primary_key": false,
"is_not_null": false
}
],
"read_only": false
}
{
"pk()": "foo",
"table_name": "foo",
"store_id": "dF9LVlljTQ==",
"field_constraints": [],
"read_only": false …
```
=> Add primary key config to tableInfo

sql/parser/select.go, sql/parser/select_test.go, sql/planner/deletion.go, sql/planner/explain_test.go, sql/planner/projection.go, sql/planner/replacement.go, sql/planner/sort.go, sql/planner/tree.go
This PR fixes the order of the nodes generated by the parser. Projections are supposed to happen before sorting and limit/offset.
```sql
EXPLAIN SELECT a + 1 FROM test WHERE c > 30 ORDER BY a DESC LIMIT 10 OFFSET 20
```
Before:
```
Table(test) -> σ(cond: c > 30) -> Sort(a DESC) -> Offset(20) -> Limit(10) -> ∏(a + 1)
```
After:
```
Table(test) -> σ(cond: c > 30) -> ∏(a + 1) -> Sort(a DESC) -> Offset(20) -> Limit(10)
```
=> Fix node order

sql/query/expr/function.go, sql/query/select_test.go
This PR adds preliminary Min and Max aggregators. They work great with scalars but behavior with array and document values is kind of random. This will be fixed once the comparison support for these types will be added.
Fixes #165, #166
=> Min Max aggregators

database/config.go, database/config_test.go, database/table.go, database/transaction.go, database/transaction_test.go, index/index.go, index/index_test.go
This PR introduces types in indexes. A typed index only accepts one type of values, this allows for several space efficient optimizations.
=> Add typed indexes

cmd/genji/main.go, cmd/genji/shell/shell.go
Calling `.exit` was causing the shell to exit immediately, without flushing the history or closing the database. This PR adds a `exit` method that does exactly that.
=> Add exit method to shell type

cmd/genji/shell/shell.go
Fixes #198 
shell commands are to be allowed the suffix of semicolon.
=> Sell command can be ended by a semicolon #198

engine/enginetest/benchmark.go
Running `go test -bench Scan` in `engine/badgerengine` panics.
See the commit message for the details.
=> Fix benchmarks for badgerengine

document/cast.go, document/cast_test.go, document/compare.go, document/compare_test.go, document/create.go, document/encoding/custom/codec.go, document/encoding/encodingtest/testing.go, document/encoding/msgpack/codec.go, document/scan_test.go, document/value.go, document/value_test.go, document/value_wasm.go, index/index.go, key/encoding.go, key/encoding_test.go, sql/parser/create_test.go, sql/parser/expr.go, sql/parser/expr_test.go, sql/query/create_test.go, sql/query/expr/literal.go, sql/query/insert_test.go, sql/scanner/scanner.go, sql/scanner/scanner_test.go, sql/scanner/token.go
The duration type was there from the beginning as a way to test multiple types. It doesn't really make sense to keep it now as `INTEGER` can do the job.
Passing a duration as a parameter, in `document.NewValue` or `document.NewFromStruct` will convert it to an INTEGER.
=> Drop duration type

sql/driver/driver.go
This PR partially addresses issue #210 by implementing the approach that relies either on Go support (see golang/go#41710) or runtime.SetFinalizer to close the underlying database. Note that the latter is non-deterministic and we can’t handle an error.
=> Implement driver.DriverContext and driver.Connector interfaces in sql/driver

cmd/genji/go.mod
Replace in `go.mod` works only for the main module.
=> Added replace rule for badgerengine in cmd/genji module

cmd/genji/shell/command.go, cmd/genji/shell/command_test.go
Fixes #233 
`command_test.go` had some errors.
`.Indexes` returns `table not found`
=> Fixes .Indexes and .tables commands error handler and tests

document/value.go, document/value_test.go
Reverts genjidb/genji#246 since the change doesn’t fix the issue for all possible values and introduces regressions.
- For some reason exponent formatting (see [encoding/json implementation](https://github.com/golang/go/blob/d4a5797b8863185230d0e89da9a00fd17f04152a/src/encoding/json/encode.go#L577-L603)) was removed.
- Checking `f == float64(int(f))` fails if f is greater than the maximum int value.
A better way would be to check [`_, frac := math.Modf(f); frac == 0`](https://golang.org/pkg/math#Modf) or [`math.Mod(f, 1) == 0`](https://golang.org/pkg/math#Mod).
```
f := 1e42
fmt.Println(f == float64(int(f)))
_, frac := math.Modf(f); fmt.Println(frac == 0)
fmt.Println(math.Mod(f, 1))
```
Alternatively, we can just insert `.0` if it’s note already there.
FWIW it’d also be nice to return an …
=> Revert "Display doubles with a decimal point"

cmd/genji/shell/command.go, cmd/genji/shell/shell.go
Changes for issue #180 
The `help` and `exit` commands work correctly when typing them, however, when typing the new commands the suggestions list won't show up and this is because of the way their [previous commands were added](https://github.com/ab22/genji/blob/master/cmd/genji/shell/command.go#L21-L22).
Also, when typing `.help` or `.exit` it now displays `.help or help` or `.exit or exit` on the suggestions. I am wondering how would you like these commands to be added to the suggestion list. Maybe an `alias []string` under the `commands` structure?
=> #180: add exit and help cmds

cmd/genji/shell/shell.go
=> Fix autocompletion panic

cmd/genji/main.go
The `genji version` command relies on the versions of modules compiled in as debug info. Those are unavailable when compiling Genji with `go get github.com/genjidb/genji/cmd/shell` (in GOPATH mode). This makes `genji version` display a message saying the version is not available if genji has been built with `go get`.
Sample output:
```
genji on master [!?] via v1.15.2 > GO111MODULE=off go run github.com/genjidb/genji/cmd/genji version
Using z.Allocator with starting ref: 8005000000000000
version not available in GOPATH mode
```
=> Do not panic on genji version when compiled in GOPATH mode

sql/parser/expr.go
This wraps the error returned by `strconv.Atoi` inside `ParseError`
Fixes #256
=> Wrap error from strconv.Atoi inside ParseError

sql/parser/expr.go
This PR ignores currently unsupported operators in `parseOperator`.
```
genji> SELECT 0 !~ 1;
found !~, expected ; at line 1, char 10
genji> SELECT 0 1;
found 1, expected ; at line 1, char 10
```
Closes #252
=> Ignore currently unsupported regex operators

.github/workflows/test-fuzz.yaml
Interrupting go-fuzz always returns non-zero error code, so we should ignore it. Check whether `crashers` directory exists instead.
=> Fix fuzz workflow failing when there are no crashers

database/config.go, database/table.go, database/table_test.go, database/transaction.go, database/transaction_test.go, sql/parser/alter.go, sql/parser/alter_test.go, sql/parser/create.go, sql/parser/create_test.go, sql/query/alter.go, sql/scanner/scanner_test.go, sql/scanner/token.go
Fixes #96.
Adds:
- New `DEFAULT` constraint which sets default value of field/column.
- `ALTER TABLE <table_name> ADD COLUMN <field definition>` statement to add new fields to the table. Original issue requests `ADD FIELD` statement, but I think `ADD COLUMN` is more compatible with SQL. Anyway, it's not too hard to fix.
I have some questions about the _correct_ table info modification.
=> Add ADD COLUMN statement, add DEFAULT field constraint

database/table.go, document/array.go, document/create.go, document/create_test.go, document/document.go, document/document_test.go, sql/query/expr/expr_test.go, sql/query/expr/path_test.go
This PR is a small, low hanging, premature optimization.
It changes the way the `document.NewFromJSON` function works by lazily decoding the json data and delegating error handling to the `Iterate` and `GetByField` methods.
This takes advantage of the `jsonparser` library and prevents from duplicating the entire json object in memory before storing it.
It's 50% faster for small objects and about 20% for large objects, and 80% more memory efficient. It might be useful later for quick stream insertion.
```
name               old time/op    new time/op    delta
JSONToDocument-12    9.17µs ± 0%    7.86µs ± 0%   ~     (p=1.000 n=1+1)
name               old alloc/op   new alloc/op   delta
JSONToDocument-12    5.65kB ± 0%    3.10kB ± 0%   ~     (p=1.000 n=1+1)
name               old allocs/op …
```
=> Slightly more efficient conversion from JSON to document

engine/badgerengine/engine_test.go, engine/badgerengine/example_test.go, engine/boltengine/engine_test.go, engine/boltengine/example_test.go, engine/enginetest/benchmark.go, engine/enginetest/testing.go
This PR ensures that we close engine before cleanup in `enginetest`. On Windows tests were failing with the following error.
<details>
```
2020/10/23 21:27:17 remove C:\Users\RUNNER~1\AppData\Local\Temp\genji245175255/badger\000000.vlog: The process cannot access the file because it is being used by another process.
github.com/dgraph-io/badger/v2/y.Wrap
github.com/dgraph-io/badger/v2@v2.2007.2/y/error.go:71
github.com/dgraph-io/badger/v2/y.Check
github.com/dgraph-io/badger/v2@v2.2007.2/y/error.go:43
github.com/dgraph-io/badger/v2.(*valueLog).createVlogFile.func1
github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1008
github.com/dgraph-io/badger/v2.(*valueLog).createVlogFile
github.com/dgraph-io/badger/v2@v2.2007.2/value.go:1022
github.com/dgraph-io/badger/v2.(*valueLog).open …
```
=> Fix badgerengine tests on Windows

rfcs/001_context.md
This PR adds an RFC about how we should use `Context` in Genji.
It is opened for comments and suggestions.
=> RFC 001: Cancelable operations and use of Context

cmd/genji/shell/command.go, database/config.go, database/config_test.go, database/table.go, database/table_test.go, database/transaction_test.go, document/document.go, document/document_test.go, sql/parser/delete_test.go, sql/parser/expr.go, sql/parser/expr_test.go, sql/parser/parser.go, sql/parser/select.go, sql/parser/select_test.go, sql/parser/update.go, sql/parser/update_test.go, sql/planner/optimizer.go, sql/planner/optimizer_test.go, sql/planner/sort.go, sql/planner/tree.go, sql/query/constraint.go, sql/query/create.go, sql/query/create_test.go, sql/query/expr/expr_test.go, sql/query/expr/path.go
Most important changes are:
- `document.ValuePath` renamed to `document.Path`
- `expr.FieldSelector` renamed to `expr.Path`
The rest is essentially renaming constructors, tests, etc.
=> Normalize naming of path related types and functions

database/database.go, database/database_test.go, database/transaction.go
This fixes #298 by making sure access to the `attachedTxMu` mutex is only locked by Commit or Rollback if that transaction is actually attached.
=> Fix deadlock with concurrent transactions

document/iterator.go, sql/planner/tree.go, sql/query/select_test.go
This PR fixes #208 by encoding values before using them as keys of the `groups` map
=> Fix grouping of lazily decoded values

database/config.go, database/database.go, database/transaction.go, database/transaction_test.go
This PR simplifies how we are handling table information. Currently, table information is loaded in memory on database startup. This was done to fix issues with concurrent table creation with the badger engine, but I believe this is not the right solution for that problem.
With this change, table information is not cached anymore and directly fetched from the engine.
=> Remove in-memory tableInfoStore

cmd/genji/shell/command.go
This PR removes duplicates `buf.Reset()`.
`byte.Buffer` is already flushed in `buf.WriteTo(w)`.
[see WriteTo](https://golang.org/src/bytes/buffer.go?s=7711:7769#L255)
=> remove duplicate Reset() of bytes.Buffer

document/iterator.go, sql/parser/select.go, sql/parser/select_test.go, sql/planner/aggregation.go, sql/planner/explain_test.go, sql/planner/projection.go, sql/planner/tree.go, sql/query/expr/function.go, sql/query/expr/path.go, sql/query/expr/path_test.go, sql/query/select_test.go
This PR improves how GROUP BY and SELECT work together. From now on, when GROUP BY is used, only aggregation functions or expressions used in the GROUP BY clause can be used in SELECT:
```sql
-- valid
SELECT COUNT(id), country FROM users GROUP BY country;
SELECT age % 10 FROM users GROUP BY age % 10;
-- invalid
SELECT COUNT(id), age FROM users GROUP BY country;
field "age" must appear in the GROUP BY clause or be used in an aggregate function
SELECT age % 10 FROM users GROUP BY age;
field "age % 10" must appear in the GROUP BY clause or be used in an aggregate function
```
This PR also adds a new Aggregation node to the planner to simplify the Projection node.
Fixes #317
=> Allow selection expression used in GROUP BY clause

cmd/genji/shell/command.go, cmd/genji/shell/command_test.go, cmd/genji/shell/shell.go
Fixes #311; These changes should cover the use case. 
There is one ambiguous part though, what do we do when the target file exists? I went for the least surprising route, just naively write all the K,V pairs over the new database, instead of let's say, removing the files or clearing all K,V pairs before writing the new ones, which could have dire consequences in case of a ctrl-c for example. 
Please tell me if you think I missed something or have any feedback!
=> Add .save command

engine/badgerengine/store.go, engine/boltengine/engine.go, engine/boltengine/store.go, engine/engine.go, engine/enginetest/testing.go, engine/memoryengine/store.go
This PR makes the engine store soft delete keys and cleanup on commit. This is done to prevent tree rebalancing when iterating and deleting at the same time, which was a problem with Bolt.
It also prevents inserting empty values in stores.
=> Soft delete store keys before commit

sql/parser/delete.go, sql/parser/delete_test.go, sql/parser/order_by.go, sql/parser/select.go, sql/query/delete_test.go, sql/query/expr/env.go, sql/query/expr/env_test.go
Hey there!
This PR fixes #318, #319 and #320. I grouped my changes to avoid having to open cascading PRs, as those clauses are dependent on each other to be properly tested (the sort operation from the order by must be done before the skip and take ones). 
I found two bugs along the way in `tx.Clone()` and added some tests for them:
- the `Tx` wasn't copied over, which broke getting the table name after sorting the stream 
- the `Vars` weren't copied properly as well 
Finally, the parsing functions for the clauses were now not just being used by the select statement, so they've been extracted in their own file. 
Please tell me if there is anything that must be fixed, changed or done in a different PR, I'll make the changes!
```
genji> EXPLAIN DELETE FROM foo ORDER BY a DESC;
{
"plan": …
```
=> Add ORDER BY, LIMIT and OFFSET clauses to DELETE statement

document/encoding/msgpack/codec.go, document/encoding/msgpack/encoding_test.go
Hello! 
Here is the fix for #349. 
If we take the output from script used in the above issue: 
_before the PR_: 
```
[129 161 97 211 0 0 0 0 0 0 0 2]
map[%!$(string=a):%!$(int64=2)]v
```
_after the PR_: 
```
[129 161 97 2]
map[%!$(string=a):%!$(int8=2)]v
```
<details><summary>Benchmark outputs</summary>
<p>
_before the PR_: 
```
~/code/src/github.com/genjidb/genji U main› go test -v -run=^\$ -benchmem -bench=. ./document/encoding/msgpack
goos: darwin
goarch: amd64
pkg: github.com/genjidb/genji/document/encoding/msgpack
BenchmarkCodec
BenchmarkCodec/Codec/Encode
BenchmarkCodec/Codec/Encode-12            227773              5279 ns/op            4601 B/op          9 allocs/op
BenchmarkCodec/Codec/Decode
BenchmarkCodec/Codec/Decode-12             84496             14296 ns/op           11552 …
```
=> Encode and decode compacted ints

sql/driver/driver.go, sql/driver/driver_test.go
=> Fix driver.Sql with Stream.Operator finder.

database/index_test.go
@asdine here is a quick PR about something I noticed while reading the code: there was an `err` that wasn't asserted in an index test.
It also silences two missing errcheck warnings in benchmarks!
=> Fix error not being asserted in test case

cmd/genji/shell/command.go
While reading the code I targeted missing errors handling of `Iterate` function in `SaveCommand`.
=> Add missing error handling in command save

database/index.go, db_test.go, planner/explain.go, planner/optimizer.go, planner/optimizer_test.go, planner/statement.go, stream/iterator.go, stream/iterator_test.go
This PR modifies the planner to use the stream.PkScan operator when possible.
This operator behaves like an index but is faster and space efficient because it uses
the table tree rather than a separate index tree.
Benchmarks:
Before
```bash
$ go test -count=5 -benchmem -run=^$ -bench BenchmarkSelectPk | tee old.txt
goos: linux
goarch: amd64
pkg: github.com/genjidb/genji
cpu: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
BenchmarkSelectPk/00001-12                 60174             17452 ns/op            4184 B/op         90 allocs/op
BenchmarkSelectPk/00001-12                 67738             17082 ns/op            4183 B/op         90 allocs/op
BenchmarkSelectPk/00001-12                 71444             16640 ns/op            4183 B/op         90 allocs/op
BenchmarkSelectPk/00001-12 …
```
=> Use PkScan operator

database/table.go, database/table_test.go, database/transaction.go, engine/boltengine/engine.go, engine/enginetest/testing.go, engine/memoryengine/engine.go, engine/memoryengine/store.go, query/update_test.go, testutil/document.go, testutil/index.go, testutil/misc.go
This fixes how UPDATE queries on indexed tables would cause some indexes to be in an incorrect state.
This was caused by the "trash bin" mechanism implemented in both bolt and memory engines, where nodes would get marked as deleted without modifying the btree and then actually removed when the transaction is committed.
The error occurred when a key was marked for deletion and then overwritten (which happens a lot when we run UPDATE on indexed fields that are not modified), the cleanup mechanism would delete them even when it's not supposed to.
This PR also fixes a race condition occurring in the memory engine.
Fixes https://github.com/genjidb/genji/issues/355
=> Fix index state with UPDATE queries

database/catalog.go, database/catalog_test.go, database/index.go, database/transaction.go, query/reindex_test.go
This PR ensures the index is build when it is created, and returns the appropriate error when failing
=> Build index upon creation

database/constraint.go, sql/parser/create.go, sql/parser/create_test.go
This adds support for the `PRIMARY KEY` table constraint:
```sql
CREATE TABLE foo(a INT, PRIMARY KEY(b))
```
Fixes #333
=> Add PRIMARY KEY table constraint

cmd/genji/shell/command.go, database/catalog.go, database/catalog_test.go, database/config.go, database/config_test.go, database/table_test.go, database/transaction.go, query/create.go, query/create_test.go, sql/parser/create.go, sql/parser/create_test.go
This allows creating indexes without specifying an index name:
Synopsis:
```
CREATE INDEX [[IF NOT EXISTS] name] ON table_name (field_name)
```
Example:
```sql
CREATE INDEX ON foo(a);
CREATE UNIQUE INDEX ON foo(a);
CREATE INDEX IF NOT EXISTS idx_foo_a ON foo(a);
```
=> Auto generate index name

database/constraint.go, database/table_test.go, query/create.go, query/create_test.go, sql/parser/create.go, sql/parser/create_test.go, sql/parser/parser.go
This adds support for the `UNIQUE` field constraint and table constraint
```sql
CREATE TABLE foo (a INT UNIQUE);
CREATE TABLE foo (a INT, UNIQUE (b));
```
=> Add support for UNIQUE constraint

.travis.yml, cmd/examplar/.gitignore, cmd/examplar/README.md, cmd/examplar/examplar.go, cmd/examplar/examplar_test.go, cmd/examplar/extest1.sql, cmd/examplar/extest1_test.go.gold, cmd/examplar/main.go, cmd/examplar/scanner.go, cmd/examplar/test_template.go.tmpl
And possibly GitHub issues, when we'll have iterated enough on it :) 
➡️ check the README for an extensive description of what it does and how it works.
To avoid messing with paths (the test template), it uses `embed` from Go 1.16. It can be an issue, and it could be fixed if needed.
=> Work out a new way to write integration tests

document/encoding/codec.go, document/encoding/custom/codec.go, document/encoding/custom/format.go, document/encoding/encodingtest/benchmark.go, document/encoding/encodingtest/testing.go, document/encoding/msgpack/codec.go, document/encoding/msgpack/encoding.go, document/encoding/msgpack/encoding_test.go, document/scan_test.go, internal/database/index.go, internal/database/table.go
The codec interface has been modified to allow the reuse of buffers when decoding
documents one by one from a table.
Memory consumption has been reduced drastically (-60%) and iteration speed has been improved by 20%
```
name                          old time/op    new time/op    delta
PreparedSelectWhere/00001-12    8.28µs ± 0%    7.24µs ± 0%  -12.51%  (p=1.000 n=1+1)
PreparedSelectWhere/00010-12    14.3µs ± 0%    12.7µs ± 0%  -11.16%  (p=1.000 n=1+1)
PreparedSelectWhere/00100-12    91.7µs ± 0%    77.3µs ± 0%  -15.65%  (p=1.000 n=1+1)
PreparedSelectWhere/01000-12     862µs ± 0%     728µs ± 0%  -15.55%  (p=1.000 n=1+1)
PreparedSelectWhere/10000-12    9.08ms ± 0%    7.34ms ± 0%  -19.13%  (p=1.000 n=1+1)
name                          old alloc/op   new alloc/op   delta …
```
=> Small performance improvements

db.go
👋 @asdine,
Genji is sweet ❤️ You rock, man.
It seems `scanDocument` only needs to call `Iterate` on `*Result`. Why not passing a `document.Iterator` instead? As the function is called `scanDocument` and returns a `document.Document`, taking a `document.Iterator` as argument looks a bit more `document` API friendly.
Cheers 🏖️
=> Use document.Iterator for scanDocument

document/document.go
In `document/FieldBuffer.Delete`, the return value of `parentPath[:len(parentPath)-1].GetValueFromDocument(fb)` is never used. I suspect a forgotten line or an unhandled case that should be handled (and I'm ready to work on this issue if so).
=> Remove unused code from document/FieldBuffer.Delete

cmd/genji/doc/doc_test.go, cmd/genji/doc/functions.go, internal/expr/functions/math.go, internal/expr/functions/testdata/math_functions.sql
See this spreadsheet for following progress on functions implementations: 
https://docs.google.com/spreadsheets/d/e/2PACX-1vQeXU_3ymhCOYL5mkeOVObTFhTuF6CNUogDXN-1sDn7Kb55GZtSJDquJw5PyX7JS_x0cLZCoxtou4AA/pubhtml
@asdine I think it's worth going step by step on those, taking the time to think about some decisions as we go through 👇 
In the context of those functions, I think we need to agree on: 
- Genji's function explicitly deal with their input validation, so we can produce readable error messages. Those are a part of the API after all. 
- Most of the mathematical functions are returning `NULL` when some arg is `NULL`. That's what PG / SQLite does, I see no reason from deviating from it.
- Functions that accept floats can take in integers, implicitly. Same as the above.
=> Add more math functions 

document/json.go, document/json_test.go, internal/expr/expr_test.go, internal/query/statement/explain_test.go, internal/query/statement/gen_select_test.go, internal/query/statement/gen_select_test.sql, internal/query/statement/select.go, internal/query/statement/select_test.go, internal/sql/parser/select.go, internal/sql/parser/select_test.go, internal/testutil/expr.go, open_test.go
This fixes a bug where using AS wouldn't rename the field
=> Fix field name when using alias

document/cast.go, document/cast_test.go, internal/expr/functions/testdata/math_functions.sql, internal/testutil/expr.go
When converting a double larger or equal to `math.MaxInt64` to an integer, it previously overflowed silently. It now returns an explicit error. 
This fixes along the way, the `math.abs(-9223372036854775808)` issue.
=> Handle integer conversion errors

internal/testutil/expr.go, internal/testutil/genexprtests/genexprtests.go
With a bunch of `t.Helpers()` and line numbering, it's now much better. Because the originating file path (the sql) is absolute, you can click on it within your editor to open it (ignore the truncated version in the example below, it's a proper path in the code). 
```
--- FAIL: TestMathFunctions (0.00s)
--- FAIL: TestMathFunctions/math.floor (0.00s)
--- FAIL: TestMathFunctions/math.floor/OK_@#math.floor(2.3) (0.00s)
math_test.go:11:
Error Trace:    expr.go:160
Error:          Received unexpected error:
found @, expected  at line 1, char 1
Test:           TestMathFunctions/math.floor/OK_@#math.floor(2.3)
Messages:       parse error at (/home/...)/testdata/math_functions.sql:2
`@#math.floor(2.3)`
--- FAIL: TestMathFunctions/math.abs (0.00s)
--- FAIL: …
```
=> Improve failures readability when testing exprs

internal/errors/error.go, internal/errors/errors.go, internal/errors/errors_debug.go, internal/errors/errors_debug_test.go, internal/errors/stackframe.go
The goal of this package is to enable to capture stack traces when the error are being raised, which speeds up the development process, if enabled at compile time. To do so, this set of changes introduces an internal/errors package to handle errors with four functions: .New, .Errorf, .Is and .Unwrap. Albeit support for reflect has been added recently to tinygo, it presently not depend on reflect in any way.
If the code is compiled with the debug build tag, the stack trace will be captured when an error is created or wrapped (both with .New). Without that build tag, the errors packages falls back to simply comparing values and performs no wrapping at all.
It also come with a new testutil/assert package which replaces the require package when it comes to checking or comparing errors and …
=> Add errors package with optional stacktrace capturing

cmd/genji/shell/command.go, cmd/genji/shell/shell.go
=> Add .timer command.

cmd/genji/commands/insert.go, cmd/genji/dbutil/insert.go
InsertJson is used to insert json data into a db but if something wrong happens we should rollback to the initial state of the database to avoid partial insertion. 
Especially in the case of the following usage. 
`curl https://api.github.com/repos/genjidb/genji/issues | genji insert --db mydb -t foo`
=> use transaction in InsertJSON

README.md
Starting in Go 1.17, installing executables with `go get` is deprecated and `go install` is preferred. Version suffix is used to let users run this command outside the module directory which makes installation of genji more universal.
I just tried to install `genji` myself and bumped into an error. Fixed commands worked fine.
=> update installation command in README.md

cmd/genji/commands/bench.go, cmd/genji/commands/dump.go, cmd/genji/dbutil/bench.go, cmd/genji/dbutil/dump.go, cmd/genji/dbutil/dump_test.go, cmd/genji/dbutil/schema.go, cmd/genji/shell/command.go, cmd/genji/shell/command_test.go, cmd/genji/shell/shell.go
Just a cleanup of unused `context.Context` input parameters
=> remove unused contexts from cmd/genji

internal/stream/docs/temp_tree_sort.go, sqltests/SELECT/order_by.sql, types/value.go
When the ORDER BY expression uses fields that are not present in the preceding projection operator,
it was evaluating the expression to NULL, which was breaking the ordering.
It now evaluates the expr against the result of the projection first, then if it is NULL
evaluates it against the original document.
Example:
```bash
table.Scan("test") | docs.Project(b) | docs.TempTreeSort(a)
```
Fixes #466
=> orderby: fix evaluation of ORDER BY expr when used with projection

cmd/genji/commands/restore.go, cmd/genji/dbutil/restore.go, cmd/genji/shell/command.go, cmd/genji/shell/shell.go
Restore command works exactly like `genji restore` ~and restarts the shell to open the database which was restored from the dump.~ and applies given dump to currently open database
~@asdine I also thought about adding a flag to decide whether:~
~1) we want to restart the shell and go to restored database~
~or~
~2) stay in current database.~
~But probably I am trying to overthink this and option 1 (which is currently implemented) is fine~
=> add .restore command

cmd/genji/doc/functions.go, internal/expr/functions/builtins.go, internal/expr/functions/testdata/builtin_functions.sql, sqltests/SELECT/len.sql
Fixes #474
I have few concerns about this PR:
* @asdine provided examples of using LEN with columns in tables. But this PR doesn't contain such tests, because tests will be required outside of `expr` package (or import of another parser will be needed). Anyway, I don't see anything bad in such test, but I don't known codebase well enough to decide is it worth it.
* Maybe error message can be improved.
* LEN function is quite expensive for ARRAY and DOCUMENT because it need to loop over elements. Probably this can be problem, but out of scope of  the mentioned issue and this PR.
=> Add LEN builtin function

README.md
Add forgotten import in example
"github.com/genjidb/genji/types"
=> Add forgotten import in example

db_test.go, document/scan.go
When decoding a document from the disk, fields of type TEXT are not copied on purpose to avoid doing unnecessary copies.
However, when the data reaches the upper layers, usually when it's about to get scanned (i.e. document.Scan, document.StructScan), strings must always get deep cloned before being returned to the user.
Fixes #497
=> fix: deep copy strings during scan

document/scan.go, document/scan_test.go
Added check that an interface parameter is a pointer to a structure in StructScan.
Refers #453
=> StructScan check interface parameter is a pointer to a struct

cmd/genji/doc/functions.go, internal/expr/functions/builtins.go, sqltests/SELECT/lower.sql
Adds LOWER to builtins functions to format TEXT fields to lower-case.
For non TEXT fields it will return NULL.
Types that can be casted to TEXT will work if they're first explicitly casted.
=> Add LOWER builtin function

cmd/genji/doc/doc_test.go, cmd/genji/doc/functions.go, internal/expr/functions/definition.go, internal/expr/functions/strings.go, sqltests/SELECT/STRINGS/ltrim.sql, sqltests/SELECT/STRINGS/rtrim.sql, sqltests/SELECT/STRINGS/trim.sql
Add the trim function and its 2 variants ltrim rtrim.
=> add trim, ltrim, rtrim functions

.gitignore, cmd/genji/doc/functions.go, internal/expr/functions/builtins.go, internal/expr/functions/definition.go, internal/expr/functions/strings.go, internal/sql/parser/parser.go, internal/stream/operator.go, sqltests/expr/coalesce.sql
This PR fixes #509 by adding support to `COALESCE` method.
Unlike PosgreSQL, our implementation doesn't fail if the arguments aren't of the same type.
However, an error is returned if there is no argument at all.
=> Add coalesce function

README.md
All these changes were needed for this quickstart example to run through without crashing
=> Fix the quickstart example so it actually works
